config/routes.rb
Rails.application.routes.draw do
  unauthenticated :user do
    root to: 'splash#index'
  end
  
  authenticated :user do
    root 'groups#index', as: :authenticated_root
  end
  
  resources :entities
  resources :groups
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entity.rb
class Entity < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :entities, dependent: :destroy

  validates_format_of :icon,
                      with: /\.(gif|jpg|png)\z/i,
                      message: 'must have an image extension'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :groups, dependent: :destroy
  has_many :entities
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:username, :email, :password, :current_password)
    end
  end
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  before_action :set_entity, only: %i[show edit update destroy]

  # GET /entities or /entities.json
  def index
    @entities = Entity.all
  end

  # GET /entities/1 or /entities/1.json
  def show; end

  # GET /entities/new
  def new
    @entity = current_user.entities.new
  end

  # GET /entities/1/edit
  def edit; end

  # POST /entities or /entities.json
  def create
    @entity = current_user.entities.new(entity_params)

    respond_to do |format|
      if @entity.save
        format.html { redirect_to groups_path, notice: 'Entity was successfully created.' }
        format.json { render :show, status: :created, location: @entity }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @entity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entities/1 or /entities/1.json
  def update
    respond_to do |format|
      if @entity.update(entity_params)
        format.html { redirect_to @entity, notice: 'Entity was successfully updated.' }
        format.json { render :show, status: :ok, location: @entity }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @entity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entities/1 or /entities/1.json
  def destroy
    @entity.destroy
    respond_to do |format|
      format.html { redirect_to groups_path, notice: 'Entity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_entity
    @entity = Entity.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def entity_params
    params.require(:entity).permit(:name, :amount, :user_id, :group_id)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[show edit update destroy]

  # GET /groups or /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1 or /groups/1.json
  def show
    @group_entities = Entity.where(group_id: params[:id]).all
  end

  # GET /groups/new
  def new
    @group = current_user.groups.new
  end

  # GET /groups/1/edit
  def edit; end

  # POST /groups or /groups.json
  def create
    @group = current_user.groups.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to groups_path, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:name, :icon, :user_id)
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entities_helper.rb
module EntitiesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
  def counter(arr)
    c = 0
    arr.each do |item|
      c += item.amount
    end
    c
  end
end

app/helpers/splash_helper.rb
module SplashHelper
end

app/views/entities/_form.html.erb
<%= form_with(model: entity) do |form| %>
  <% if entity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(entity.errors.count, "error") %> prohibited this entity from being saved:</h2>

      <ul>
        <% entity.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field card-body">
    <%= form.select :group_id, Group.all.collect { |x| [x.name, x.id]},{ :include_blank => 'Select group'},class:"form-control-sm form-control"%>
  </div>
  <div class="card-body">
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name,class:'form-control' %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.text_field :amount,class:'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit class:'btn btn-sm btn-primary mt-2' %>
  </div>
  </div>
<% end %>

app/views/entities/edit.html.erb
<h1>Editing Entity</h1>

<%= render 'form', entity: @entity %>

<%= link_to 'Show', @entity %> |
<%= link_to 'Back', entities_path %>

app/views/entities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Entities</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Amount</th>
      <th>User</th>
      <th>Group</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @entities.each do |entity| %>
      <tr>
        <td><%= entity.name %></td>
        <td><%= entity.amount %></td>
        <td><%= entity.user_id %></td>
        <td><%= entity.group_id %></td>
        <td><%= link_to 'Show', entity %></td>
        <td><%= link_to 'Edit', edit_entity_path(entity) %></td>
        <td><%= link_to 'Destroy', entity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Entity', new_entity_path %>

app/views/entities/new.html.erb
<div class="card">
    <div class="card-header">
        <h4>New Transaction</h4>
    </div>
<%= render 'form', entity: @entity %>
</div>

app/views/entities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @entity.name %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @entity.amount %>
</p>

<p>
  <strong>User:</strong>
  <%= @entity.user_id %>
</p>

<p>
  <strong>Group:</strong>
  <%= @entity.group_id %>
</p>

<%= link_to 'Edit', edit_entity_path(@entity) %> |
<%= link_to 'Back', entities_path %>

app/views/groups/_form.html.erb
<%= form_with(model: group) do |form| %>
  <% if group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="card-body">
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, class:'form-control' %>
  </div>

  <div class="field">
    <%= form.label :icon %>
    <%= form.text_field :icon, class:'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit class:'btn btn-primary btn-sm mt-2' %>
  </div>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<div class="col-lg-5 col-sm-12 mt-2">
    <% @groups.each do |group| %>
      <div class="d-flex flex-row justify-content-around bg-white rounded m-lr shadow p-2 mb-1">
        <div>
          <%=image_tag group.icon,class: 'rounded-circle', size: "160" %>
        </div>
        <div>
          <p class="text-muted"><%= group.name %></p>
          <p class="text-muted"><%= group.created_at %></p>
           <%= link_to 'Group Entities', group_path(group),class:'btn btn-outline-info btn-sm'%>
          <%if current_user == group.user%>
            <%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' },class:'btn btn-sm btn-outline-danger' %>
          <%end%>
        </div>
      </div>
    <%end%>
      <%= link_to 'New Group', new_group_path, class:'buttonSpecial btn btn-success btn-lg btn-block w-100'%>
    </div>

app/views/groups/new.html.erb
<div class="card">
  <div class="card-header">
    <h4>New Group</h4>
</div>
<%= render 'form', group: @group %>
</div>
<div class="card-footer">
<%= link_to 'Back', groups_path %>
</div>

app/views/groups/show.html.erb
<div class="shadow d-flex justify-content-center p-2 mb-3 bg-white rounded">
  <p class="text-muted">Credit: <%=counter(@group_entities)%><p>
</div>

<% @group_entities.each do |item| %>
  <div class="d-flex bg-white rounded m-lr flex-row justify-content-around shadow p-2 mb-1">
    <div>
      <%=image_tag Group.find(params[:id]).icon, class: 'rounded-circle', size: "130" %>
    </div>
    <div class="">
      <p class="text-muted">
      Author: <%=item.user.username%> | 
      <%= item.name %>
      </p>
      <p class="text-muted"><%= item.created_at %></p>
      <%if current_user == item.user%>
        <%= link_to 'Edit', edit_entity_path(item),class:'btn btn-sm btn-outline-primary'%>
        <%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' },class:'btn btn-sm btn-outline-danger' %>
      <%end%>
    </div>
    <div>
        <p class="text-dark">Amount: <%= item.amount %></p>
    </div>
  </div>
<%end%>
<div class="card spec-1">
<%= link_to 'Add a new transaction', new_entity_path, class:'btn btn-lg btn-primary mt-2' %>
<%= link_to 'Back', groups_path, class:'btn btn-primary btn-lg mt-2' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render partial: "shared/navbar" %>
  <%= render partial: "shared/msg" %>
  <div>
    <%= yield %>
  </div>
</html>

app/views/shared/_msg.html.erb
<% if notice  %>
<div class="alert alert-warning" role="alert">
  <%= notice %>
</div>
<% end  %>
<% if alert  %>
<div class="alert alert-danger" role="alert">
  <%= alert %>
</div>
<% end  %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-color">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      <%if user_signed_in?%>
        <%= link_to 'All groups', groups_path,class:'nav-link text-light' %>
      <%end%>
      </ul>
      <div class="d-flex navbar-nav">
        <%if user_signed_in?%>
            <%= link_to current_user.username, edit_user_registration_path,method: :get,class:'nav-link text-light'%>
            <%= link_to 'Sign Out', destroy_user_session_path,method: :delete,data: {confirm:'Are you sure?'},class:'nav-link text-light'%>
        <%else%>
            <%= link_to 'Sign In', new_user_session_path,class:'nav-link text-light'%>
            <%= link_to 'Sign Up', new_user_registration_path,class:'nav-link text-light'%>
        <%end%>
      </div>
    </div>
  </div>
</nav>

app/views/splash/index.html.erb
<div class = "splash">
  <h1 class = "text-center ">Budget App</h1>
  <div class="text-center d-flex flex-column">
    <%= link_to 'Sign In', new_user_session_path,class:'btn btn-primary btn-lg spec'%>
    <%= link_to 'Sign Up', new_user_registration_path,class:'btn btn-primary btn-lg spec'%>
  </div>
</div>